const sentences = [
  // ["Dutch sentence...", "Answer"],
  ["’s Avonds doe ik mijn ring af. Ik leg mijn ring altijd...", "op tafel"],
  [
    "Aaliyah pakt eerst een kopje koffie. Daarna gaat ze...",
    "een broodje eten",
  ],
  ["Aaron gaat donderdag op reis. Hij vindt dat...", "leuk"],
  ["Aaron is dokter. Hij werkt...", "in het ziekenhuis"],
  ["Aaron is schilder. Hij schildert meestal...", "bloemen"],
  [
    "Abdul stuurt zijn familie elke week een e-mail. Hij schrijft dan over...",
    "zijn leven",
  ],
  ["Abel is op school. Hij heeft...", "engels"],
  ["Achmed is klaar met school. Hij gaat...", "werken"],
  ["Adam is aan het koken. Hij maakt...", "frikandel"],
  [
    "Ahmed brengt zijn zoon naar het vliegveld. Zijn zoon gaat...",
    "naar Madrid",
  ],
  ["Aiden is bij de bakker. Hij wil...", "croissants"],
  ["Alec gaat naar school. Hij wil graag...", "leren"],
  ["Alex gaat altijd met de trein. Ik ga graag met...", "de bus"],
  ["Alex is ziek. Hij heeft pijn aan...", "zijn hoofd"],
  ["Alex wil nieuwe schoenen. Hij gaat naar...", "het centrum"],
  ["Ali kan niet goed lopen. Hij heeft pijn aan zijn...", "voeten"],
  ["Ali werkt in een fabriek. Hij wil...", "stoppen"],
  ["Alice werkt in een ziekenhuis. Zij is daar...", "dokter"],
  ["Amel sport graag. Sporten is...", "leuk"],
  ["Ana is niet blij met haar huis. Ze vindt haar huis...", "klein"],
  ["Ananda is aan het koken. Ze maakt...", "lasagna"],
  ["Andres werkt op het land. Het werk is...", "zwaar"],
  ["Anisa maakt huiswerk op de computer. Ze doet dat...", "goed"],
  ["Anna is bij de dokter. Ze krijgt...", "pillen"],
  ["Anna’s huis is te klein. Ze wil snel...", "verhuizen"],
  ["Anna wast de paprika. Ze gaat…", "koken"],
  ["Arif wacht op de bus. De bus komt...", "laat"],
  ["Arjun moet elke dag reizen naar zijn werk. Hij werkt in...", "Utrecht"],
  ["Arnold is schoonmaker. Hij werkt in...", "Utrecht"],
  ["Ayla eet haar ontbijt snel op. Ze heeft...", "Honger"],
  ["Aziz loopt elke dag. Hij loopt naar...", "zijn huis"],
  ["Barry is geslaagd voor zijn examen. Hij krijgt...", "cadeau's"],
  ["Bart gaat bijna elke dag met de auto. Hij rijdt dan naar...", "huis"],
  ["Berat geeft les. Hij vertelt over...", "talen"],
  ["Bilal gaat naar de bioscoop. Hij gaat met zijn...", "vriend"],
  ["Bob houdt niet van zwemmen. Hij gaat liever...", "kanoën"],
  ["Brenda doet een opleiding. Ze moet iedere avond...", "leren"],
  ["Brian fietst naar zijn werk. Hij gaat liever niet…", "lopen"],
  ["Cai werkt met hout. Hij maakt...", "tafels"],
  ["Carla drinkt een glas water. Ze doet dat...", "snel"],
  ["Carlos gaat vroeg slapen. Hij is...", "moe"],
  ["Carlos is vrij. Hij gaat...", "fietsen"],
  ["Carlos maakt muziek. Hij doet dat...", "graag"],
  ["Carmen eet elke dag een banaan. Soms eet ze ook...", "appels"],
  ["Caro eet vaak appels. Zij houdt ook van…", "aardbeien"],
  ["Caro gaat vaak met de bus naar school. Soms gaat ze...", "fietsen"],
  ["Chen verkoopt bloemen. Ze doet dat...", "graag"],
  ["Chris heeft een computer. Hij gebruikt de computer om te...", "leren"],
  ["Chris neemt zijn pillen. Hij heeft pijn in zijn...", "hoofd"],
  ["Christina belt met haar moeder. Ze praten over...", "haar leven"],
  ["Christo heeft dorst. Hij drinkt een glas...", "water"],
  ["Claire kijk uit het raam. Ze kijkt naar...", "buiten"],
  ["Claire leert Nederlands. Ze vindt Nederlands...", "mooi"],
  ["Dael heeft veel geld. Hij werkt...", "vaak"],
  ["Dafne kan goed zingen. Ze kan ook goed...", "dansen"],
  ["Daniël heeft pijn aan zijn kies. Hij gaat naar...", "de tandarts"],
  ["Daniëlle gaat studeren. Ze pakt haar...", "boeken"],
  ["Dany heeft hoofdpijn. Ze wil...", "slapen"],
  ["Dario zit op school. Hij maakt een...", "presentatie"],
  ["Dave is niet blij met zijn haar. Zijn haar is...", "rood"],
  ["Dave lust geen koffie. Hij drinkt liever...", "water"],
  ["Dave werkt in een café. Hij moet daar...", "koffie maken"],
  ["David en Maria rijden naar de stad. Ze zoeken...", "de supermarkt"],
  ["David heeft een boot. Hij gebruikt de boot om te...", "varen"],
  ["David is dik. Hij eet elke dag...", "chocolade"],
  ["David werkt in een ziekenhuis. Hij is...", "dokter"],
  ["De auto van Leah is kapot. Ze brengt de auto naar...", "de garage"],
  ["De baas van Patrick is boos. Patrick vindt dat...", "niet leuk"],
  ["De broer van Souad heeft een baby gekregen. Souad is...", "oom"],
  ["De bus is vaak te laat. Paul vindt dat...", "niet leuk"],
  ["De bus rijdt langzaam. Lia wil...", "naar huis"],
  ["De dochter van Sophia kijkt veel tv. Ze kan beter gaan...", "fietsen"],
  ["De dokter praat met Sofia. De dokter geeft Sofia...", "pillen"],
  ["De familie Wang woont in een leuke straat. Zij wonen naast...", "een park"],
  ["De kinderen lezen samen. In het boek staat...", "veel tekst"],
  ["De klas is leeg. Iedereen is...", "buiten"],
  ["De koning is op het nieuws. Hij vertelt over...", "Nederland"],
  ["De les begint om 11 uur. Hetty gaat...", "naar school"],
  ["De les is afgelopen. We willen nu...", "naar huis"],
  ["De man belt in de auto. Dat is...", "niet goed"],
  ["De stoel is kapot. Jaimy gaat de stoel...", "maken"],
  ["De trein is vol. Hanna moet...", "staan"],
  ["De zoon van Samira gaat naar school. Samira vindt dat...", "goed"],
  ["Debra zit op school. Ze maakt veel…", "huiswerk"],
  ["Die sinaasappel is oud. Je moet de sinaasappel...", "weggooien"],
  ["Diego houdt van koken. Hij kookt graag voor...", "zijn familie"],
  ["Dimitri werkt in een garage. Hij maakt...", "auto's"],
  ["Dina wast haar handen. Haar handen zijn…", "vies"],
  ["Dunya gaat naar een feest. Het feest is van haar...", "vrienden"],
  ["Dylan is bij de tandarts. Dat is...", "niet leuk"],
  ["Edgar en Joko koken samen. Ze doen dat...", "graag"],
  ["Een mug heeft mij geprikt. Nu krijg ik...", "pijn"],
  ["Eliza is morgen jarig. Haar vader…", "koopt een cadeau"],
  ["Ella bakt koekjes. Ze bakt de koekjes voor...", "haar vriend"],
  ["Emma doet een opleiding. Dat is...", "slim"],
  ["Emma schrijft alles op. Daarna gaat ze...", "leren"],
  ["Emma wast haar handen. Ze gaat...", "koken"],
  ["Er is ingebroken bij Ben. Hij belt naar...", "de politie"],
  ["Er komen nieuwe huizen in onze buurt. Ik vind dat...", "niet leuk"],
  ["Er ligt rommel op straat. Dat is...", "niet leuk"],
  ["Esma wil lerares worden. Zij gaat...", "studeren"],
  ["Esra is ziek. Ze vindt dat...", "niet leuk"],
  ["Fanya is op de markt. Ze zoekt...", "aardbeien"],
  ["Farid is zanger. Hij moet vandaag...", "zingen"],
  ["Fatima koopt een fiets. Ze gaat met de fiets naar…", "huis"],
  ["Fausia stapt uit de boot. Ze loopt naar...", "huis"],
  ["Felipe houdt van lezen. Hij koopt elke maand...", "boeken"],
  ["Felix gaat elke dag zwemmen. Soms gaat hij ook...", "fietsen"],
  ["Fico woont ver van zijn werk. Hij moet elke dag...", "veel rijden"],
  ["Filip maakt de badkamer schoon. Hij vindt dat...", "leuk"],
  ["Filiz koopt een nieuwe jas. Ze koopt ook...", "schoenen"],
  ["Finn kijkt nu televisie. Hij gaat straks...", "sporten"],
  ["Franco gaat verhuizen. Zijn nieuwe huis heeft een...", "garage"],
  ["Frank leest de krant. Hij leest over..", "het weer"],
  ["Fred gaat naar school. Hij heeft les tot...", "laat"],
  ["Gabriel maakt een opdracht. Hij doet dat...", "goed"],
  ["Gary leest zijn dochter voor. Lezen is...", "goed"],
  ["Gary woont bij het strand. Hij wil het liefst...", "verhuizen"],
  ["Gina kijkt vaak televisie. Ze houdt van programma's over...", "natuur"],
  ["Grace houdt niet van groente. Ze vindt dat...", "niet lekker"],
  ["Halil rijdt in een vrachtwagen. Hij vindt dat...", "leuk"],
  ["Han heeft zijn diploma gehaald. Hij gaat nu...", "werken"],
  ["Hannah eet graag vis. Ze haalt die vis...", "vers"],
  ["Hannah leert Nederlands. Ze leert ook...", "Engels"],
  ["Hannah maakt haar huis schoon. Ze doet dat...", "graag"],
  ["Harold is niet alleen. Hij heeft...", "bezoek"],
  ["Harry is gevallen. Hij heeft...", "pijn"],
  ["Hassan maakt zijn brommer. Het wiel is...", "kapot"],
  ["Hassan werkt in een restaurant. Hij leert daar...", "koken"],
  ["Het bord van Sahid is gevallen. Sahid is...", "niet blij"],
  ["Het eten is heel warm! Je moet...", "oppassen"],
  ["Het fruit is op. Ik ga nu naar...", "de markt"],
  ["Het huis van Tania is heel groot. Haar huis heeft...", "veel kamers"],
  ["Het is donker. Ik reis dan liever niet met...", "de auto"],
  ["Het is druk in de stad. Er zijn veel...", "fietsers"],
  ["Het is druk op de weg. Emir vindt dat...", "niet leuk"],
  ["Het is druk op het station. Er zijn veel...", "mensen"],
  ["Het is koud in het huis van Faiz. Hij wil...", "opwarmen"],
  ["Het is slecht weer. Gaan we met de...?", "auto"],
  ["Het is stil in de klas. De leerlingen...", "leren"],
  ["Het is warm vandaag. Ana wil...", "zwemmen"],
  ["Het is zondag. Eva gaat op zondag altijd naar...", "de kerk"],
  ["Het regent al de hele dag. William wil...", "fietsen"],
  ["Het regent onderweg. Marta wil...", "stoppen"],
  ["Het vliegveld is ver weg. We gaan naar het vliegveld met...", "de auto"],
  ["Hetty is klaar met koken. Ze roept...", "haar man"],
  ["Hiba houdt van katten. Ze houdt niet van…", "honden"],
  ["Hue wil naar de markt. Ze gaat...", "fietsen"],
  ["Ibrahim heeft een kar met spullen. Hij brengt de spullen...", "naar huis"],
  ["Iedereen is blij. Het is...", "kerst"],
  ["Ik ben op zoek naar het treinstation. Kunt u mij...", "helpen"],
  ["Ik ben ziek. Ik ga morgen niet...", "werken"],
  ["Ik drink geen alcohol. Ik drink wel graag...", "cola"],
  ["Ik eet graag brood. Ik houd niet van...", "kaas"],
  ["Ik eet nooit druiven. Ik vind druiven...", "niet lekker"],
  ["Ik eet nooit kip. Dat vind ik...", "niet lekker"],
  ["Ik ga een taart maken. Wil jij...?", "ook"],
  ["Ik ga morgen brood kopen. Brood koop ik meestal...", "op maandag"],
  ["Ik ga naar de huisarts. Hij geeft mij...", "pillen"],
  ["Ik ga naar mijn zus. Mijn zus woont...", "in Utrecht"],
  ["Ik ga straks naar Hamza. Hij is...", "ziek"],
  ["Ik ga vaak met de bus. Ik ga dan naar...", "Utrecht"],
  ["Ik heb deze krant gelezen. Wil jij de krant nu..?", "lezen"],
  ["Ik heb een computer met internet. Die gebruik ik...", "veel"],
  ["Ik heb een nieuwe tafel gekocht. Wil jij mijn oude tafel...?", "hebben"],
  ["Ik heb geen auto. Een auto is...", "duur"],
  ["Ik heb soep gemaakt. Wil jij mijn soep...?", "hebben"],
  ["Ik heb wortels gekocht. Ik koop de wortels voor...", "mijn moeder"],
  ["Ik houd van tekenen. Ik teken...", "graag"],
  [
    "Ik lees het nieuws op mijn telefoon. Mijn man leest het nieuws...",
    "in de krant",
  ],
  ["Ik lees vaak. Ik lees graag...", "boeken"],
  ["Ik wil zieke mensen helpen. Ik vind dat...", "goed"],
  ["Imani vindt school leuk. Zij houdt van...", "leren"],
  ["In de stad rijden veel brommers. Ik vind dat...", "niet leuk"],
  ["In een grote stad wonen veel mensen. Ik vind dat...", "niet leuk"],
  ["In het eten zitten pepers. Ik vind dat...", "niet lekker"],
  ["Inez en Luis bouwen een huis. Het huis heeft nog geen...", "deur"],
  ["Inez gaat naar een concert. Ze gaat...", "met vrienden"],
  ["Is dat boek leuk? Ik wil het boek ook graag...", "lezen"],
  ["Isa heeft pauze. Ze belt met haar...", "vriend"],
  ["Isabel speelt graag met haar pop. Soms speelt ze ook met...", "haar broer"],
  ["Ismet heeft groenten in zijn tuin. Hij gaat de groenten...", "eten"],
  ["Ivan is niet blij met zijn werk. Hij vindt zijn werk te...", "zwaar"],
  ["Iwan wil gezond zijn. Hij drinkt geen...", "cola"],
  ["Jack koopt tomaten. Hij koopt ook...", "aardbeien"],
  ["Jack wil de muziek niet horen. Hij vindt de muziek...", "niet mooi"],
  ["Jacques is leraar. Hij geeft...", "les"],
  ["Jada maakt pannenkoeken voor haar familie. Zij doet dat...", "graag"],
  ["Jafar houdt niet van dansen. Hij vindt dansen...", "niet leuk"],
  ["Jakob zoekt een taxi. Hij wil...", "naar huis"],
  ["Jamal heeft een nieuwe scooter. Hij kan nu...", "rijden"],
  ["Jamal woont in een flatgebouw. Hij wil graag...", "verhuizen"],
  ["Jamila maakt kleding. Die kleding is voor...", "zijn familie"],
  ["Jan heeft zijn arm gebroken. Hij moet nu...", "rusten"],
  ["Janek heeft koorts. Zijn moeder geeft hem...", "pillen"],
  ["Janine leert Nederlands. Ze praat met de lerares over...", "de woorden"],
  ["Jara is zwanger. Ze krijgt...", "een kind"],
  ["Jasmine gaat naar het ziekenhuis. In het ziekenhuis zijn...", "dokters"],
  ["Jason gaat graag naar school. Hij kan goed...", "leren"],
  ["Jessie houdt van muziek. Ze speelt graag...", "piano"],
  ["Jessie moet langer werken vandaag. Ze mag pas om acht uur...", "naar huis"],
  ["Jessy koopt een kaartje. Ze gaat…", "naar de bioscoop"],
  ["Jie is op de markt. Hij ziet...", "aardbeien"],
  ["Jim gaat naar het strand. Het is daar...", "mooi"],
  ["Jim heeft haast. Hij moet snel naar...", "huis"],
  ["Jim staat voor de school. Hij wacht op…", "zijn moeder"],
  ["Jing maakt de borden schoon. Daarna gaat ze...", "relaxen"],
  ["Joel heeft een vieze keuken. Hij moet...", "schoonmaken"],
  ["Johan heeft veel boeken. Hij houdt van…", "lezen"],
  ["Johanna doet suiker in haar koffie. Suiker is...", "lekker"],
  ["John en zijn dochter bakken samen taart. Ze vinden dat...", "leuk"],
  ["John houdt van paarden. Hij vindt paarden...", "leuk"],
  ["John woont bij een bos. Hij gaat daar elk weekend...", "fietsen"],
  ["Johnny is moe. Hij wil...", "slapen"],
  ["Johnny is vrij op zaterdag. Hij gaat...", "fietsen"],
  ["Jonas werkt altijd buiten. Dat is...", "koud"],
  ["Josh heeft de hele dag gelopen. Hij wil nu...", "relaxen"],
  ["Josh koopt een krant in de winkel. Hij koopt ook...", "kibbeling"],
  ["Judy leest een tijdschrift. Soms leest ze ook...", "de krant"],
  ["Julio gaat verhuizen. Hij moet...", "schoonmaken"],
  ["Karim heeft pijn in zijn rug. Hij moet...", "rusten"],
  ["Karim leest het weerbericht. Het weer wordt...", "mooi"],
  ["Karima gaat naar de dokter. Ze voelt zich...", "niet lekker"],
  ["Karin kijkt naar het journaal. Ze doet dat...", "elke dag"],
  [
    "Karl gaat met zijn dochter naar de dierentuin. Ze kijken naar...",
    "olifanten",
  ],
  ["Katya volgt een opleiding. Ze wil...", "dokter worden"],
  ["Kay zoekt een nieuw huis. Hij vindt zijn oude huis...", "te klein"],
  ["Kei eet 's avonds met zijn familie. Dat vindt hij...", "gezellig"],
  ["Kenji rookt al twintig jaar sigaretten. Dat is...", "niet goed"],
  ["Kenny zoekt op internet. Hij zoekt naar...", "werk"],
  ["Kevin eet een salade met paprika. In de salade zit ook...", "aardappel"],
  ["Kevin heeft huiswerk. Hij moet veel...", "maken"],
  ["Kevin werkt in een restaurant. Hij maakt vandaag...", "lasagne"],
  ["Kevin zit in de klas. Hij heeft een vraag over...", "engels"],
  ["Khalid is visser. Na het werk is hij vaak...", "moe"],
  ["Kris werkt in de tuin. Hij doet dat…", "graag"],
  ["Kun je mij een lepel geven? Ik wil...", "eten"],
  ["Kun je mij naar het station brengen. Ik moet op tijd...", "komen"],
  ["Kwasi is chauffeur. Hij rijdt...", "graag"],
  ["Laila moet elke dag vroeg opstaan. Soms is ze...", "laat"],
  ["Laiqa werkt elke dag buiten. Ze houdt van...", "mooi weer"],
  ["Laura heeft veel collega's. Ze gaan samen...", "eten"],
  ["Lea eet graag in een restaurant. Ze vindt dat...", "lekker"],
  ["Lea gaat naar haar kleinzoon. Ze geeft hem...", "cadeau's"],
  ["Lea is in het ziekenhuis. Ze wil...", "naar huis"],
  ["Lei speelt op straat. Dat is...", "leuk"],
  ["Leon is verkouden. Hij moet...", "niezen"],
  ["Leon speelt gitaar. Hij doet dat...", "graag"],
  [
    "Leyla slaapt samen met haar zus in een kamer. Zij vinden dat...",
    "niet leuk",
  ],
  ["Li en Chen gaan iets drinken. Ze drinken...", "koffie"],
  ["Lia wil meer geld voor haar werk. Dan kan ze...", "op vakantie"],
  ["Liam kan niet goed zien. Hij moet...", "lenzen"],
  ["Lily gaat elke dinsdag sporten. Ze eet daarna altijd...", "kibbeling"],
  ["Lin zoekt werk. Ze gaat naar...", "randstad"],
  ["Ling wil iets eten. Ze eet liever geen...", "koolhydraten"],
  ["Linn heeft niet goed geslapen. Ze blijft...", "thuis"],
  ["Liyen gaat vanavond koken. Ze gaat eerst...", "schoonmaken"],
  ["Lizzie en haar moeder gaan met het vliegtuig. Lizzie vindt dat...", "leuk"],
  ["Loes is ziek. Zij gaat vandaag…", "slapen"],
  ["Louis gaat op de scooter naar zijn werk. Hij doet dat...", "graag"],
  ["Louis gebruikt de computer. Hij wil...", "leren"],
  ["Lucia heeft haar been gebroken. Nu kan ze niet...", "lopen"],
  ["Lucia wil nieuw werk. Ze vindt haar oude werk...", "niet leuk"],
  ["Madee heeft een auto. Ze gaat met de auto naar...", "huis"],
  ["Mae heeft een nieuwe auto. Ze kan nu...", "op vakantie"],
  ["Mag ik jouw brommer lenen? Mijn brommer is...", "kapot"],
  ["Mai kijkt niet naar het nieuws. Ze vindt het nieuws...", "niet leuk"],
  ["Maja maakt soep. De soep is...", "lekker"],
  ["Malik gaat vandaag niet sporten. Hij heeft geen...", "zin"],
  ["Malik heeft een nieuwe bank gekocht. De oude bank was...", "kapot"],
  ["Mandy eet vaak chips als ze een film kijkt. Ze eet soms ook...", "popcorn"],
  ["Manuel is buschauffeur. Hij rijdt...", "graag"],
  ["Marco heeft zin in koffie. Hij wil ook...", "een koekje"],
  ["Marco is ziek. Hij belt...", "de huisarts"],
  ["Maria heeft griep. Ze moet...", "rusten"],
  ["Maria kan goed koken. Ze kookt meestal...", "lasagne"],
  ["Maria leest een boek. Ze vindt het...", "leuk"],
  ["Maria leest op zondag de krant. Ze leest soms...", "een boek"],
  ["Mariam praat met de leraar. Mariam praat ook met haar...", "vrienden"],
  ["Martin eet elke ochtend een ei. Zijn vrouw eet meestal...", "brood"],
  ["Martin stelt een vraag aan de docent. De vraag gaat over...", "nederlands"],
  ["Maryam kookt voor Dina. Maryam maakt...", "lasagne"],
  ["Masha kan vandaag zitten in de bus. Soms moet ze...", "staan"],
  ["Max draagt een helm op zijn werk. Dat moet van zijn...", "moeder"],
  ["Max voetbalt graag. Voetballen is…", "leuk"],
  ["Maya doet de gordijnen dicht. Ze gaat...", "slapen"],
  ["Megan gaat vandaag verhuizen. Ze woont straks...", "in Utrecht"],
  ["Melissa wacht op het station. Ze wacht op haar...", "moeder"],
  ["Mevrouw Perez heeft geen auto meer. Nu moet ze...", "fietsen"],
  ["Mia maakt zelf kleren. Vandaag maakt ze een...", "T-shirt"],
  ["Mia moet snel naar huis. Ze gaat met de...", "bus"],
  ["Michael houdt niet van tennis. Hij houdt meer van...", "voetbal"],
  ["Michelle kijkt vaak films. Ze houdt van films over...", "drama"],
  ["Michelle maakt huiswerk. Ze vindt het huiswerk...", "niet leuk"],
  ["Miguel stopt met werken. Hij is...", "moe"],
  ["Mijn auto is kapot. Nu moet ik...", "fietsen"],
  ["Mijn baas fietst elke dag. Ik doe dat...", "nooit"],
  ["Mijn benzine is op. Nu moet ik...", "fietsen"],
  ["Mijn broer houdt niet van varen. Hij wordt altijd ziek op...", "water"],
  ["Mijn broer zingt veel. Hij is...", "niet goed"],
  ["Mijn buurman maakt graag muziek. Dat vind ik...", "niet leuk"],
  ["Mijn opa gaat elke dag wandelen. Dat is...", "goed"],
  ["Mijn opa zit op de bank. Hij kijkt naar...", "Netflix"],
  ["Mijn telefoon is kapot. Nu kan ik niet...", "whatsappen"],
  ["Mijn trein vertrekt over een half uur. Ik ga nu...", "lopen"],
  ["Mijn vader heeft een paard. Hij gaat...", "paardrijden"],
  ["Mijn vader loopt met een stok. Mijn vader is...", "oud"],
  [
    "Mijn vader luistert graag naar het nieuws. Hij luistert ook naar...",
    "de radio",
  ],
  ["Mijn zus rijdt altijd hard. Ik vind dat...", "niet goed"],
  ["Mike heeft pijn aan zijn been. Hij heeft ook pijn aan zijn...", "arm"],
  ["Mina werkt bij de supermarkt. Ze werkt daar…", "graag"],
  ["Ming rijdt vaak op zijn scooter. Hij wil niet...", "fietsen"],
  ["Mira heeft zin in koffie. Ze drinkt koffie met...", "melk"],
  ["Mo en zijn familie spelen een spel. Daarna gaan ze...", "eten"],
  ["Mo zit aan tafel. Hij schrijft een brief aan zijn...", "moeder"],
  ["Mohammed maakt auto’s. Dat vindt hij...", "leuk"],
  ["Monica maakt graag foto's. Ze maakt het liefst foto's van...", "eten"],
  ["Monica wil graag een huis met een tuin. Ze vindt dat...", "mooi"],
  ["Myra en Liz gaan naar een café. Ze willen graag...", "lasagne"],
  ["Nadia heeft kip gekocht. Ze gaat de kip eerst...", "schoonmaken"],
  ["Naima wil kapper worden. Ze leert...", "knippen"],
  ["Nancy en Oscar zitten in de bioscoop. Ze vinden de film...", "leuk"],
  ["Nasir zoekt een nieuw huis. Hij wil een huis met...", "een tuin"],
  ["Nasira woont bij de supermarkt. Ze woont ook bij...", "water"],
  ["Nick wil naar zijn familie. Hij reist met...", "de bus"],
  ["Nick zoekt werk. Hij wil graag werken bij...", "jumbo"],
  ["Nicole gaat naar de tandarts. Ze heeft pijn aan haar...", "kies"],
  ["Nikki zoekt een nieuw huis. Ze wil graag...", "verhuizen"],
  ["Nina speelt in de tuin. Ze speelt met...", "lego"],
  ["Noah leest een bericht in de krant. Het bericht gaat over...", "het weer"],
  ["Noor werkt in een winkel. Ze verkoopt broeken en ook...", "schoenen"],
  ["Nora en Souffian wonen in een dorp. Ze wonen liever...", "in utrecht"],
  ["Odara ruimt het huis op. Ze legt de kleren...", "in de kast"],
  ["Olga is ziek. Ze moet...", "rusten"],
  ["Omar koopt vis. Hij koopt ook...", "aardbeien"],
  [
    "Omid leest 's ochtends altijd eerst de krant. Daarna gaat hij...",
    "fietsen",
  ],
  ["Ons dak is kapot. Wij moeten...", "verhuizen"],
  ["Orma heeft leuke buren. Ze gaat met haar buren...", "eten"],
  ["Pablo gaat vaak met de trein. Hij gaat dan naar...", "Utrecht"],
  ["Pablo speelt gitaar. Hij oefent...", "graag"],
  ["Pari gaat elke dag met de bus. Vandaag gaat ze...", "fietsen"],
  ["Pascal vindt zijn werk moeilijk. Hij wil...", "stoppen"],
  ["Paul gaat vroeg naar bed. Hij moet morgen...", "werken"],
  ["Paul heeft honger. Zijn moeder geeft hem...", "een broodje kaas"],
  ["Paul viert zijn verjaardag. Hij is...", "blij"],
  ["Paula heeft een brief gekregen. De brief is van...", "zijn moeder"],
  ["Pedro doet de lamp aan. Het is...", "laat"],
  ["Pedro woont op een boerderij. Hij heeft daar...", "familie"],
  ["Peter maakt machines. Hij werkt vaak...", "hard"],
  ["Peter speelt met zijn zoon. Ze zijn...", "blij"],
  ["Philip fietst op de weg. De weg is...", "lang"],
  ["Philippa zit in de tuin. Ze zit ook vaak...", "binnen"],
  ["Pia woont naast een park. Ze gaat daar...", "lopen"],
  ["Priya doet een opleiding. Later wordt ze...", "dokter"],
  ["Priya maakt saus. Haar dochters willen...", "helpen"],
  ["Quito eet vandaag niet thuis. Hij eet...", "bij zijn vriendin"],
  ["Rachel zingt vaak alleen. Soms zingt ze ook...", "samen"],
  ["Rafael heeft een telefoon. Hij belt elke dag met zijn...", "moeder"],
  ["Raheem heeft een fijn huis. Hij woont daar met...", "vriend"],
  ["Rahime heeft Nederlandse les. Ze vindt haar docent...", "leuk"],
  ["Rasha werkt op een kantoor. Het kantoor is...", "mooi"],
  ["Remi werkt op de markt. Hij verkoopt…", "kip"],
  ["Rhonda is haar sleutel kwijt. Nu moet ze...", "lopen"],
  ["Rico eet vaak snoep. Snoep is slecht voor...", "je"],
  ["Rico krijgt een prik. Hij is...", "ziek"],
  ["Rima en haar dochter zijn in de keuken. Haar dochter wil...", "taart"],
  ["Robin loopt snel naar school. Hij is...", "laat"],
  ["Romeo werkt op een school. Hij geeft les aan...", "Engels"],
  ["Roy wil zijn vriend spreken. Hij gaat...", "verhuizen"],
  ["Ryan heeft weinig geld. Hij werkt...", "veel"],
  ["Ryan wil een film zien. Hij gaat naar...", "de bioscoop"],
  ["Sabir heeft een nieuwe baan. Hij werkt bij...", "de Jumbo"],
  ["Saïd heeft vakantie. Hij gaat...", "naar Spanje"],
  ["Saïd is te laat op zijn werk. Zijn baas is...", "niet blij"],
  ["Salih is bakker. Hij werkt meestal...", "in de ochtend"],
  ["Salim snijdt de uien. Zijn vrouw gaat...", "koken"],
  ["Sam is vandaag op school. Hij gaat straks naar…", "leren"],
  ["Sam loopt het lokaal uit. Hij gaat...", "naar huis"],
  ["Samir is te laat voor de trein. Hij moet nu...", "fietsen"],
  ["Samira heeft een gesprek met haar baas. Ze praten over...", "geld"],
  ["Samira gaat naar haar ouders. Ze gaan samen...", "heeft vakantie"],
  ["Samira heeft pijn aan haar rug. Ze kan niet goed...", "lopen"],
  ["Samuel heeft vandaag les. Hij gaat morgen...", "werken"],
  ["Samuel praat met zijn baas. Hij vraagt...", "vrij"],
  ["Samuel vindt de pauze leuk. Hij gaat dan...", "eten"],
  ["Sandra moet vandaag veel doen. Ze moet...", "werken"],
  ["Sanne kan niet goed koken. Het eten is...", "niet lekker"],
  ["Sara lacht. Zij is…", "blij"],
  ["Sara praat met haar buurvrouw. Ze praten over...", "heer familie"],
  ["Sarah is nooit ziek. Zij voelt zich altijd...", "goed"],
  ["Sari zoekt een cursusboek. Ze gaat naar...", "de oba"],
  ["Sarina reist met de bus. Zij gaat naar…", "huis"],
  ["Sasha eet niet altijd thuis. Ze gaat vaak naar...", "een restaurant"],
  ["Sasha gaat naar de bioscoop. Ze kijkt...", "een film"],
  ["Sasha heeft een hond. Ze heeft ook...", "een kat"],
  ["Savita gaat solliciteren. Ze wil...", "werken"],
  ["Scott doet een opleiding. Hij vindt leren...", "leuk"],
  ["Selim kan zijn broer niet bellen. Hij stuurt zijn broer een...", "email"],
  ["Shaila draagt een rugzak naar school. In de rugzak zit...", "het boek"],
  ["Shanna heeft haar diploma. Ze is...", "blij"],
  ["Shing heeft zijn arm gebroken. Hij mag niet...", "rijden"],
  ["Shun wil niet eten. Hij wil liever...", "spelen"],
  ["Siham volgt een cursus. Ze leert...", "Nederlands"],
  ["Simon bouwt een huis. Het huis wordt...", "groot"],
  ["Simon wil leraar worden. Hij moet veel...", "studeren"],
  ["Simone leest graag een krant. Ze koopt hem...", "elke dag"],
  ["Sita bakt een taart. Haar kinderen vinden…", "dat lekker"],
  ["Sita geeft taart aan haar opa. Hij vindt dat...", "lekker"],
  ["Sjaak werkt in een fabriek. Daar werkt hij...", "graag"],
  ["Sonia zit in de bus. Ze gaat naar...", "Utrecht"],
  ["Sonya houdt van muziek. Ze luistert...", "de radio"],
  ["Sophia houdt van rijst. Ze kookt dat...", "elke dag"],
  ["Sophie is vaak in het bos. Ze kijkt graag naar...", "de maan"],
  ["Sou eet graag maïs. Ze eet maïs meestal met...", "kaas"],
  ["Souad koopt bananen op de markt. Ze koopt ook...", "aardbeien"],
  ["Stanley wil een groter huis. Hij wil ook...", "verhuizen"],
  ["Stefan belt met zijn zus. Zijn zus is...", "spaans"],
  ["Stefana vindt wandelen leuk. Ze doet dat...", "elke dag"],
  ["Stephan moet sporten van de dokter. Hij gaat...", "fietsen"],
  ["Steven is in het ziekenhuis. Hij gaat morgen...", "naar huis"],
  ["Sven komt uit het ziekenhuis. Hij is...", "moe"],
  ["Sylvia is kapper. Ze moet vandaag veel...", "werken"],
  ["Tamal moet remmen. Hij ziet een...", "kat"],
  ["Tanya is bakker. Ze verkoopt...", "taart"],
  ["Tara wil een motor kopen. Een motor is...", "duur"],
  ["Tara zoekt werk. Ze kijkt in...", "de krant"],
  ["Tariq eet alleen. Hij vindt dat...", "ongezellig"],
  ["Tess eet veel fruit. Fruit is...", "lekker"],
  ["Thirza wil later in het ziekenhuis werken. Ze moet eerst...", "studeren"],
  ["Thomas ligt in het ziekenhuis. Hij vindt dat...", "niet leuk"],
  ["Tim drinkt graag koffie. Hij drinkt liever koffie dan…", "water"],
  ["Tim is jarig. Zijn zus geeft hem een...", "cadeau"],
  ["Tirza koopt een nieuw bed. Ze koopt ook...", "kussens"],
  ["Tony eet brood. Hij eet het brood met...", "kaas"],
  ["Tuan zit op school. Hij heeft volgende week...", "examens"],
  ["Veel mensen praten in de les. Nena vindt dat...", "niet leuk"],
  ["Vera doet suiker in haar thee. Haar thee wordt zo...", "zoet"],
  ["Victor heeft een nieuw huis. Hij gaat morgen...", "verhuizen"],
  ["Wayan drinkt koffie met zijn buurman. Hij vindt dat...", "gezellig"],
  ["We gaan mijn broer ophalen. Hij heeft geen...", "auto"],
  ["Wij willen wat leuks doen. We gaan...", "naar de bar"],
  ["Wil je mijn huis zien? Ik woon hier...", "sinds kort"],
  ["Wil jij op mijn kinderen passen? Ik ga vanavond...", "uit"],
  ["William neemt een drankje. Dat helpt tegen...", "de dorst"],
  ["Xuan is in de supermarkt. Ze wil...", "aardbei"],
  ["Yaira werkt bij een apotheek. Ze werkt daar...", "graag"],
  ["Younes heeft veel vrienden. Hij gaat vaak met ze naar...", "de bar"],
  ["Yun eet 's ochtends niet veel. Ze eet dan alleen...", "soep"],
  ["Yvonne doet haar spullen in dozen. Zij gaat morgen…", "verhuizen"],
  ["Zarina moet de vis eerst schoonmaken. Daarna gaat ze hem...", "koken"],
  ["Zina kookt met veel kruiden. Zo wordt haar eten...", "lekker"],
  ["Zola maakt het huis schoon. Ze doet dat...", "goed"],
];

const container = document.getElementById("sentence-container");

sentences.forEach((item, index) => {
  const row = document.createElement("div");
  row.className = "row";

  // Number, sentence, toggle, answer
  row.innerHTML = `
        <span class="number">${index + 1}.</span>
        <span class="dutch">${item[0]}</span>
        <label class="switch-label">
            <input type="checkbox" class="toggle-answer">
        </label>
        <span class="correct-answer" style="opacity:0;width:60px; ">${
          item[1]
        }</span>
    `;

  // Toggle answer visibility
  row.querySelector(".toggle-answer").addEventListener("change", function () {
    const answer = row.querySelector(".correct-answer");
    answer.style.opacity = this.checked ? "1" : "0";
  });

  container.appendChild(row);
});
